version: "4"

services:
  aelfgpt:
    build:
      context: .
      dockerfile: Dockerfile.aelfgpt
      target: prod
    image: aelfgpt:${AELT_GPT_VERSION:-latest}
    container_name: aelfgpt
    restart: always
    env_file:
      - .env
    depends_on:
      - ollama
    environment:
      AELF_GPT_HOST: 0.0.0.0
    networks:
      - aelfnet

  ollama:
    image: ollama/ollama:latest
    ports:
      - 7869:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - aelfnet

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    volumes:
      - ./ollama/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 7070:8080
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://host.docker.internal:7869 #comma separated ollama hosts
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=AelfGPT Admin
      - WEBUI_URL=http://localhost:8080
      - WEBUI_SECRET_KEY=t0p-s3cr3t
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - aelfnet

networks:
  aelfnet: