# ATLAS_URI username and password has been made available so that the embeddings may be accessed

ATLAS_URI = "mongodb+srv://azeezbalogun74:9ZmoOy3k67XE6pOt@cluster0.nzbehil.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

GEMINI_API_KEY = ""